version: '3'

services:
  database:
    image: "mysql:8.0.21"
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      -  ./vmr-docker/vmr-database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  cache:
    image: "redis:6.0.6"
    ports:
      - "6379:6379"
  envoy:
    build: 
      context: ./vmr-docker/vmr-envoy
      dockerfile: ./dockerfile
    network_mode: host
  promotheus:
    build:
      context: ./vmr-docker/vmr-prometheus
      dockerfile: ./dockerfile
    network_mode: host
