server:
  port: 8080
  wsPort: 8081
  grpcPort: 8082
  prometheusPort: 8088
  host: 0.0.0.0
auth:
  token: dsjkshd8y2387yuhfsghduhgf673tfsgfjhg76tg3yugfshjg
  expire: 86400
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: password
  database: vmrchat
  poolSize: 50
  timeout: 120
  queueSize: 1000
cache:
  timeToLive: 120
  numMessagesCached: 20
vertx:
  numOfWorkerThread: 50
