rest:
  port: 8080
  host: 0.0.0.0
auth:
  token: dsjkshd8y2387yuhfsghduhgf673tfsgfjhg76tg3yugfshjg
  expire: 86400
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: password
  database: vmrchat
  poolSize: 15