rest:
  port: 8080
  host: 127.0.0.1
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: password
  database: vmrchat
  poolSize: 15
redis:
  host: 127.0.0.1
  port: 6379
service:
  jwtSecret: iuwiuy87y4387y4ugfsudgf3766tu43g
